#profile: dev
server:
  port: 0

spring:
  application:
    name: first-service-provider
  rabbitmq:
    host: 116.196.113.170
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      discovery:
        enabled: false
# actuator management
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
# actuator info
info:
  app:
    encoding:UTF-8
    java.source:1.8
    java.traget:1.8
    name:provider1
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://zipkin-server:9411/
    locator:
      discovery:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://cloudServerSlave1:8781/eureka/,http://cloudServerSlave2:8782/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG
