server:
  port: 8781
eureka:
  client:
    service-url:
      defaultZone: http://cloudServerSlave2:8782/eureka/
  instance:
    hostname: cloudServerSlave1
  server:
    enable-self-preservation: false
