# actuator management
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

# actuator info
info:
  app:
    encoding:UTF-8
    java.source:1.8
    java.traget:1.8
spring:
  application:
    name: first-cloud-server
