server:
  port: 0
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/linshenkx/spring-cloud-config-repo.git
          username: 15588741@qq.com
          password: ***

eureka:
  client:
    service-url:
      defaultZone: http://cloudServerSlave1:8781/eureka/,http://cloudServerSlave2:8782/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}